[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput --clear --verbosity=2"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --access-logfile - --error-logfile -"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
NIXPACKS_PYTHON_VERSION = "3.11"