# Generated by Django 5.2.11 on 2026-04-19 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('stat', 'Statistics Card'), ('chart', 'Chart'), ('table', 'Data Table'), ('list', 'List'), ('calendar', 'Calendar'), ('notification', 'Notifications'), ('custom', 'Custom HTML')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('small', 'Small (1/4 width)'), ('medium', 'Medium (1/2 width)'), ('large', 'Large (3/4 width)'), ('full', 'Full Width')], default='medium', max_length=20)),
                ('user_role', models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('accountant', 'Accountant')], default='admin', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('data_source', models.CharField(blank=True, help_text='URL or model method to fetch data', max_length=200)),
                ('chart_config', models.JSONField(blank=True, default=dict, help_text='Chart.js configuration')),
                ('refresh_interval', models.IntegerField(default=0, help_text='Refresh interval in seconds (0 for no refresh)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_role', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('metric_value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='healthy', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Health',
                'ordering': ['metric_name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('row', models.IntegerField(default=0)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardwidget')),
            ],
            options={
                'ordering': ['row', 'column', 'position'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('grid', 'Grid Layout'), ('masonry', 'Masonry Layout'), ('columns', 'Columns Layout')], default='grid', max_length=20)),
                ('widget_positions', models.JSONField(blank=True, default=dict)),
                ('theme', models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('auto', 'Auto (System Default)')], default='light', max_length=20)),
                ('color_scheme', models.CharField(default='blue', max_length=50)),
                ('compact_mode', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL)),
                ('widgets', models.ManyToManyField(through='dashboard.DashboardWidgetPosition', to='dashboard.dashboardwidget')),
            ],
            options={
                'ordering': ['-is_default', 'user__username'],
            },
        ),
        migrations.AddField(
            model_name='dashboardwidgetposition',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userdashboard'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('print', 'Print'), ('download', 'Download')], max_length=20)),
                ('app_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='dashboard_a_user_id_510456_idx'), models.Index(fields=['app_name', '-timestamp'], name='dashboard_a_app_nam_da480e_idx'), models.Index(fields=['action', '-timestamp'], name='dashboard_a_action_776181_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidgetposition',
            unique_together={('dashboard', 'widget')},
        ),
    ]
