# Generated by Django 5.2.11 on 2026-04-19 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('student', 'Student Report'), ('class', 'Class Report'), ('attendance', 'Attendance Report'), ('result', 'Result Report'), ('finance', 'Finance Report'), ('teacher', 'Teacher Report'), ('custom', 'Custom Report')], max_length=20)),
                ('file', models.FileField(upload_to='reports/generated/')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('student', 'Student Report'), ('class', 'Class Report'), ('attendance', 'Attendance Report'), ('result', 'Result Report'), ('finance', 'Finance Report'), ('teacher', 'Teacher Report'), ('custom', 'Custom Report')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('termly', 'Termly')], max_length=20)),
                ('filters', models.JSONField(default=dict)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
    ]
